    ###
POST http://localhost:8080/api/usuarios/registro
Content-Type: application/json

{
  "nombre": "samuel andres castaño",
  "cedula": "1095268216",
  "telefono": "3192325795",
  "correo": "samuel@gmail.com",
  "fechaNacimiento": "2005-02-23",
  "rol": "ANFITRION"
}

###

GET http://localhost:8080/api/usuarios/detalle/samuel@gmail.com

### Registrar opinión
POST http://localhost:8080/opiniones
Content-Type: application/json

{
  "usuarioId": "u1",
  "alojamientoId": "a1",
  "reservaId": "r1",
  "calificacion": 5,
  "comentario": "Excelente, muy cómodo y limpio."
}

### Cancelar reserva activa
PUT http://localhost:8080/reservas/cancelar/res-10
Accept: application/json

### Cancelar reserva finalizada
PUT http://localhost:8080/reservas/cancelar/res-11
Accept: application/json

### Cancelar reserva ya cancelada
PUT http://localhost:8080/reservas/cancelar/res-12
Accept: application/json

### Cancelar reserva inexistente
PUT http://localhost:8080/reservas/cancelar/res-inexistente
Accept: application/json


### Obtener historial de reservas de un usuario existente
GET http://localhost:8080/reservas/usuario/user-123
Accept: application/json

###

### Intentar obtener historial de un usuario inexistente
GET http://localhost:8080/reservas/usuario/user-no-existe
Accept: application/json