    ###
POST http://localhost:8080/api/usuarios/registro
Content-Type: application/json

{
  "nombre": "samuel andres castaño",
  "cedula": "1095268216",
  "telefono": "3192325795",
  "correo": "samuel@gmail.com",
  "fechaNacimiento": "2005-02-23",
  "rol": "ANFITRION"
}

###

GET http://localhost:8080/api/usuarios/detalle/samuel@gmail.com

### Registrar opinión
POST http://localhost:8080/opiniones
Content-Type: application/json

{
  "usuarioId": "u1",
  "alojamientoId": "a1",
  "reservaId": "r1",
  "calificacion": 5,
  "comentario": "Excelente, muy cómodo y limpio."
}
